spring:
  application:
    name: llm
  ai:
    vectorstore:
      redis:
        initialize-schema: true
        # Redis 中向量索引的名称：用于存储和检索向量数据的索引标识符，所有相关的向量搜索操作都会基于这个索引进行
        index-name: ai_knowledge_index
        # Redis 中存储向量数据的键名前缀：这个前缀会添加到每个存储在 Redis 中的向量数据键名前，每个 document 都是一个 hash 结构
        prefix: "ai:knowledge_segment:"